### ISSUE TITLE
Android - Background  color of picker's popup dialog issue

### ISSUE THREAD

**Issue by aliklev** [exponent/exponent#15]
Background  color of picker's popup dialog issue (always dark) and only in exponent container,
tested in 11.0.1 version
![untitled](https://cloud.githubusercontent.com/assets/16597961/20176666/80054112-a751-11e6-8054-3a80a9d91594.png)

**Comment by brentvatne** [comment]
@aliklev - can you provide the code you used for this? cc @jesseruder

**Comment by datwheat** [comment]
I have the same issue. Exponent v12 I'm using it with tcomb-form-native -> https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/select.android.js

![Picker](https://dl2.pushbulletusercontent.com/Z0GBfXv79tyYsZKuft5AHw1FkQXd5FLR/Screenshot_20161217-191739.png)

I let @ccheever know that this can be changed here -> https://github.com/exponentjs/exponent/blob/master/android/app/src/main/res/values/styles.xml

And ways to do it are prescribed here -> http://stackoverflow.com/questions/38921492/how-to-style-the-standard-react-native-android-picker/39141949#39141949

**Comment by brentvatne** [comment]
resolved in latest version of exponent!
