### ISSUE TITLE
AirGoogleMaps

### ISSUE THREAD

**Issue by sonaye** [exponent/exponent#16]
The IOS app needs an update to link the AirGoogleMaps library which was introduced in the latest version of react-native-maps, this way `<MapView provider='google' />` can be used to view Google Maps on IOS. At the moment, when using `provider='google'` in Exponent the app crashes.

Instructions are available [here](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#ios).

**Comment by brentvatne** [comment]
we have decided for the moment to not include this. if there is enough demand we will reconsider!

**Comment by sonaye** [comment]
Any particular reasons? Google Maps are way much better and more mature than Apple's (especially outside the US). I was actually waiting for the support to drop with SDK 12, i mean .. isn't it a straightforward integration?

**Comment by brentvatne** [comment]
it is simple but it adds to the app size for everybody. i hadn't considered that google maps works much better outside of north america, that's a good point. cc @terribleben @ide

**Comment by chownation** [comment]
+1 for Google Maps on iOS






On Thu, Dec 22, 2016 at 4:12 PM -0500, "Brent Vatne" <notifications@github.com> wrote:












it is simple but it adds to the app size for everybody. i hadn't considered that google maps works much better outside of north america, that's a good point. cc @terribleben @ide

**Comment by sonaye** [comment]
@brentvatne wondering how big of a margin are we talking about in terms of the added size? and yes, google maps are much wide spread, apple maps have practically zero data in my region.

**Comment by tjkang** [comment]
same thought with @sonaye. i also want exponent to add google maps.

**Comment by alexprice91** [comment]
I have to have it. Should we just use react-native-maps directly?

**Comment by AndrewIngram** [comment]
Lack of ability to do this is the main reason I can't use Exponent. My design requires that I have custom styles for the map tiles, which is possible with Google Maps, but not Apple Maps.

**Comment by sonaye** [comment]
@brentvatne did you revisit this? any chance of getting our hands on it with sdk 14? we are almost ready to ship and this is one of the very few areas where there is an inadequacy, switching to google maps within a web view is just bad.

**Comment by terribleben** [comment]
We ran into some Exponent-specific complications getting this running well, so it's going to miss the initial SDK 14 release next week. The tentative plan is to get it working in one of the subsequent minor updates (so you don't have to wait all the way until SDK 15).

**Comment by alexprice91** [comment]
Great, thank you!!

**Comment by chownation** [comment]
+1






On Thu, Feb 9, 2017 at 12:37 PM -0500, "Ben Roth" <notifications@github.com> wrote:












We ran into some Exponent-specific complications getting this running well, so it's going to miss the initial SDK 14 release next week. The tentative plan is to get it working in one of the subsequent minor updates (so you don't have to wait all the way until SDK 15).

**Comment by terribleben** [comment]
Support for AirGoogleMaps was included in today's iOS release, v1.13.1. This will work in SDK 14 projects, there is no new SDK version.

When developing in the Exponent app, this should just work if you add `provider="google"` to your map components. For standalone apps, exp.json now supports [ios.config.googleMapsApiKey](https://docs.getexponent.com/versions/latest/guides/configuration.html#googleMapsApiKey) to provide your own key.

Furthermore, it recently came to my attention that Apple's MapKit has a bunch of nasty memory leaks. So I definitely recommend switching over to Google Maps.
