### ISSUE TITLE
Request: add support for additional contact information using the Contact API

### ISSUE THREAD

**Issue by cavneb** [exponent/exponent#18]
See https://github.com/exponentjs/exponent/blob/master/ios/Exponent/Versioned/Modules/Api/EXContacts.m#L56

I would like to have the ability to import additional contact information that returns data similar to this library: https://github.com/rt2zz/react-native-contacts

```{
  recordID: 1,
  company: "",
  emailAddresses: [{
    label: "work",
    email: "carl-jung@example.com",
  }],
  familyName: "Jung",
  givenName: "Carl",
  jobTitle: "",
  middleName: "",
  phoneNumbers: [{
    label: "mobile",
    number: "(555) 555-5555",
  }],
  thumbnailPath: "",
}```

Thanks!

**Comment by grabbou** [comment]
It's going to be very similar. The only difference is that we express lack of value with `null` instead of an empty string.

**Comment by brentvatne** [comment]
done
