### ISSUE TITLE
Support audio playback

### ISSUE THREAD

**Issue by ohtangza** [exponent/exponent#29]
Audio playback also should be supported in Exponent as with video play.

**Comment by ohtangza** [comment]
Found this one: https://github.com/brentvatne/play-sounds

**Comment by jesseruder** [comment]
We're working on this! Should be available in one of the next SDKs

**Comment by terribleben** [comment]
[Basic audio support](https://docs.getexponent.com/versions/latest/sdk/audio.html) was released with SDK 14, and we plan to continue expanding the feature set.
