### ISSUE TITLE
native-base doesn't work

### ISSUE THREAD

**Issue by acornejo** [exponent/exponent#32]
Seems to be a problem with react-native-vector-icons.

Somehow it gets rewritten to fetch the icons form an exponent repository, which then fails to find.

![screenshot_20170102-232718](https://cloud.githubusercontent.com/assets/83786/21601903/11a99296-d144-11e6-965a-751e4a5ba7f5.png)

**Comment by cyprusglobe** [comment]
did you by chance ```run```  ```npm install @exponent/vector-icons --save-dev``` or ```yarn add @exponent/vector-icons``` inside your project?

**Comment by acornejo** [comment]
@cyprusglobe I did install @exponent/vector-icons, although I had not done the --save-dev (i.e. it was not in package.json). However AFAIK that should not make a difference.

the error stems from the following line in Icon.js (part of native-base):

```
import Ionicons from 'react-native-vector-icons/Ionicons';
``` 

I repeated the same steps in a clean project and it still doesn't work, although I get a slightly different error:

![screenshot_20170104-204853](https://cloud.githubusercontent.com/assets/83786/21669313/75f3e338-d2bf-11e6-8625-01456c1e8232.png)

**Comment by acornejo** [comment]
Finally made these work. Several things were missing.

First, exp.json had to be modified to include "ttf" in assetExts.

That got me past the first few errors.

Next, the native-base package (the version listed in the original exponent blog post advertising working UI toolkits), depends on the roboto font for its default theme.

For that to work I needed the following wrapper on the app:

```
class Wrapper extends React.Component {
  state = { fontsAreLoaded: false };

  async componentWillMount() {
    await Exponent.Font.loadAsync({
      'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf')
    });
    this.setState({fontsAreLoaded: true});
  }

  render() {
    if (this.state.fontsAreLoaded)
      return <App/>;
    else
      return <Exponent.Components.AppLoading/>;
  }
}```

The blog post was misleading since it implied that native-base would work without any special tweaks beyond doing npm install native-base, this was not the case. Summarizing required steps were:

- Edit exp.json to tweak asset extensions
- Install exponent/vector-icons
- Load roboto font using exponent's load-async.

**Comment by hafizio** [comment]
https://github.com/exponent/nativebase-example
