### ISSUE TITLE
Error loading any Exponent

### ISSUE THREAD

**Issue by ishu3101** [exponent/exponent#43]
When I try to load any exponent on an iPhone running iOS 9, I'm getting this error message: "**There was a problem loading the experience**". When I click `Show Details`, I displays this message.

```
exp://exp:host/@exponent/pomodoro
"This experience could not be verified." (code undefined)
```

**Comment by ishu3101** [comment]
The issue has been fixed after updating the app to version 1.12.1.

**Comment by skabbes** [comment]
Mabye close the PR?

**Comment by jpca999** [comment]
I get the same issue, how do i fix it ?

**Comment by ide** [comment]
What version of the Expo client and what OS are you on? What does the error message say?

**Comment by jpca999** [comment]
![image](https://user-images.githubusercontent.com/1026325/27361428-5e1eeeb0-55f5-11e7-9204-0696626b584b.png)

**Comment by ide** [comment]
Thanks - and what about on your phone?

**Comment by jpca999** [comment]
@ide  latest software I just updated today -  iphone 6s by Apple

**Comment by ide** [comment]
What about the version of the Expo client on your phone? And could you also post a screenshot of the error you see?

**Comment by jpca999** [comment]
Expo client iphone app  =  1.16.3 


![img_0010](https://user-images.githubusercontent.com/1026325/27361693-25c62928-55f7-11e7-8749-903ea28c6653.PNG)

![img_0009](https://user-images.githubusercontent.com/1026325/27361691-21edbea6-55f7-11e7-8932-c4fb920a2a64.PNG)

![img_0008](https://user-images.githubusercontent.com/1026325/27361687-1e24f3fc-55f7-11e7-9e0e-c8b8ed865e0f.PNG)

**Comment by jpca999** [comment]
@ide ALso i tried chaning the gear box options next to Url..  nothing worked.

**Comment by ide** [comment]
@jpca999 This is a different error ("no experience found") than in the original post's ("this experience could not be verified"). To debug your issue I would recommend trying this:

1. Close your project in XDE and open it again.
2. Try to load the URL in your browser on your computer (switch out `exp://` for `http://`). If that works, the development server is up and running.
3. Try to load the URL from your phone's browser to make sure your phone can reach your development server.
4. Lastly, open the URL in the Expo client.

**Comment by jpca999** [comment]
I thank you for your reply @ide I'll give it a shot asap.

**Comment by jpca999** [comment]
@ide, do you want the repo so you can try debugging what was the cause with this ?

**Comment by jpca999** [comment]
I think this could be node modules issue.. Can i replace all my npm pacakges with yarn ? sorry not too familiar with Yarn...    Heres my package.json 

{
  "name": "jobs-x-14",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "main.js",
  "dependencies": {
    "expo": "17.0.0",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",
    "react-native-elements": "^0.13.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.0",
    "redux-thunk": "^2.2.0"
  }
}

**Comment by MiLeung** [comment]
I've been getting this error on both the simulator and physical device on multiple occasions and it just seems to sort itself out randomly. Snack works fine though. This is an extremely frustrating developer experience.
