### ISSUE TITLE
iOS, facebook: logInWithReadPermissionsAsync fails with behavior = browser

### ISSUE THREAD

**Issue by skabbes** [exponent/exponent#45]
SDK version 12
iOS 10.2.1
Standalone app

When running this code:

```javascript
await Exponent.Facebook.logInWithReadPermissionsAsync(fbAppId, {
  permissions: ['public_profile', 'email'],
  behavior: 'browser',
});
```

This behavior successfully launches Safari, and if I have no facebook login stored in Safari, will prompt me for my facebook credentials.  If I am already logged-in to facebook, it will show me the "you have already authorized ....".  In either case, I press 'ok' and am presented with this screen.

![2017-01-23 11 33 30](https://cloud.githubusercontent.com/assets/592178/22220839/3658385a-e165-11e6-9c66-eaae425b35c2.png)

The login process never completes, if I press "Done" it is registered as a cancelled facebook login.

This exact behavior also happens with `behavior: 'system'` and I assume `behavior: 'native'` if there is no facebook account linked to iOS or no native facebook app installed.

**Comment by skabbes** [comment]
This could very easily be an issue with my facebook app configuration, or possibly a bug with the iOS SDK bundled with Exponent.  Happy to help triage as best as I can.

**Comment by skabbes** [comment]
Closing, this bug can no longer be reproduced on exponent 13.0.X.

**Comment by hpsoar** [comment]
Hello, I'm looking for solutions that share code between iOS & Android, and the solution from Dropbox of using C++ sounds the most safe way to do so.

I also noticed the report about your solution was published in 2014, so I want to know are you still sticking to this solution, and if it will be a good choice to get into this solution.

Thanks, BR.
