### ISSUE TITLE
Native Code Link in README Broken

### ISSUE THREAD

**Issue by kuza55** [exponent/exponent#46]
The link to the native code documentation is broken: https://docs.getexponent.com/versions/v12.0.0/guides/changing-native-code.html

I am interested in using exponent, but I will need a bunch of native code components and would like to know what the roadmap is for the near future.

**Comment by jesseruder** [comment]
The link has been updated to https://docs.getexponent.com/versions/v13.0.0/guides/exponentkit.html. Sorry about that!
