### ISSUE TITLE
Does/will exponent allow linking (i.e. 'react-native link')

### ISSUE THREAD

**Issue by JulianKingman** [exponent/exponent#56]
I love the quick setup time and configuration of exponent, but I'm hesitant to jump in without the ability to link libraries. I see [in the docs](https://docs.getexponent.com/versions/v13.0.0/guides/exponentkit.html#exponentkit) that you can use ExponentKit to 'detach' an app, but I'm wondering if it's possible to do basic linking without that. Many modules respond to `react-native link`, allowing for things like built-in fonts (I'm not a fan of async fonts) and other native functionality. Is it possible to do this somehow, or is 'detaching' the way?

**Comment by terribleben** [comment]
Hi there! A normal Exponent project is completely written in JS, so there isn't a way to modify native libraries (which is what `react-native link` does). We designed ExponentKit with the goal of allowing users to address this constraint. So yeah, if `react-native link` is required for you, you should detach to ExponentKit.

We think many native libraries are better implemented in JS anyway (e.g. loading fonts) so this is also a philosophical choice. The ExponentKit guide talks a bit more about that.

**Comment by JulianKingman** [comment]
Ah, bummer. I understand how that makes things more standardized, but it's like telling someone "we'll help you build your house faster, you just can't use these brands of doors or windows". `react-native link` is becoming a pretty standard way to connect libraries, so consider this a feature request :)

**Comment by terribleben** [comment]
You can already use `react-native link`. You just need to do it with ExponentKit. What feature exactly are you requesting?

**Comment by JulianKingman** [comment]
One way it could work is to have a `links` property in `exp.json`, so you could do something like this:
````javascript
// exp.json
{
  "links": {
    "assets": [ "/assets/font.ttf"],
    "packages": ["native-npm-package"],
  }
}
````
Then the links would be added to the native bundle. If that's not possible within the exponent app itself, it would still be cool if assets loaded asynchronously within exponent, and then include the native modules to the packaged app.

**Comment by terribleben** [comment]
The "link" in `react-native link` refers to linking code dependencies. I think you are asking if there is a way to bundle local assets in an Exponent app. In that case, maybe you would be interested in [this guide](https://docs.getexponent.com/versions/v13.0.0/guides/assets.html#all-about-assets).

**Comment by brentvatne** [comment]
Hi @JulianKingman!

There are a couple of things worth mentioning here:

- If you want to load your fonts synchronously before displaying your app, you can follow the pattern here: https://github.com/exponent/new-project-template/blob/master/main.js#L30-L70 -- this downloads and caches your font while the splash screen is being displayed, and then renders the app. If you've already downloaded the font (anytime after first load), then it is instant.

- I think that having an option to bundle assets in the ipa/apk for standalone apps would be valuable so everything you need can be downloaded when you get the app from App/Play Store, we haven't got around to that yet so hopefully downloading and caching while the splash screen is up will work for you!

**Comment by JulianKingman** [comment]
@brentvatne that's a cool pattern, I'll give it a shot, and I didn't know about the caching, which is another bonus. I think your 2nd point is right-on, but also linking has broader usages beyond just assets. For example, one of my current projects links these things:
- assets (i.e. fonts)
- react-native-fabric (I realize exponent has it's own system for this, but maybe it wouldn't need to)
- react-native-snackbar (uses native components, behind-the-scenes)
- react-native-vector-icons
- realm

These add necessary native code that links their package into the build, extending the built-in react native native functionality (like initializing realm).

**Comment by JulianKingman** [comment]
Just to add, this could reduce a lot of overhead for exponent as you wouldn't need built in unique exponent functions for everything (like fabric, facebook, etc... although those are pretty cool as direct exponent extensions.).

**Comment by jesseruder** [comment]
@JulianKingman yeah, we're aware of the advantages of `react-native link`. Fundamentally we have one binary that's in the App Store and Play Store and so we can't support `react-native link` for people who are using that binary. If you want custom native code you can use ExponentKit and compile it yourself.

**Comment by JulianKingman** [comment]
Good point about the binary, I didn't think of that. In that case, maybe it would be helpful to have a list of "exponent-safe" or "exponent-recommended" packages, perhaps searchable/installable via the XDE? I don't know, you guys are doing a great job and it seems like it's just a technical limitation that we have to live with.

**Comment by jesseruder** [comment]
Yeah that's a good idea. We're definitely open to doing something like that.

**Comment by andela-cofor** [comment]
@terribleben does expo allow `react-native link react-native-youtube` if no why ?

**Comment by jesseruder** [comment]
Please see the docs for ExpoKit @andela-cofor https://docs.expo.io/versions/latest/guides/detach.html. Expo supports `react-native link` in detached projects.

**Comment by faustoct** [comment]
@jesseruder it's not working with RNFetchBlob when running on XDE. It worked when running on Xcode.

**Comment by faustoct** [comment]
Also the documentation is kind trick. It suggests `native link` should be supported. It does mean it is supported.

**Comment by jesseruder** [comment]
@faustoct `react-native link` is supported in detached apps. I'd recommend reading these docs: https://docs.expo.io/versions/latest/guides/detach.html

**Comment by faustoct** [comment]
@jesseruder, worked. Had to recreate my project, move files, then detach with ExpoKit option.

**Comment by Skylnt** [comment]
Help me. 
https://docs.expo.io/versions/latest/guides/detach.html inactive.

**Comment by craigcosmo** [comment]
> ## This answer was updated in 2018
> * Expo supports `react-native link` if you [detach to ExpoKit](https://docs.expo.io/versions/latest/guides/expokit.html).
> * If you are looking for the unrelated topic of linking/deep linking, [Expo](https://docs.expo.io/versions/latest/guides/linking.html) and [React Native](https://facebook.github.io/react-native/docs/linking.html) both support that as well.
> 
.

the links are dead
