### ISSUE TITLE
Organizing Platform Specific code

### ISSUE THREAD

**Issue by ChenLi0830** [exponent/exponent#66]
Hi there, thank you for creating this project. :)

I might have missed something obvious here, but I didn't find any documentations about on how to make an exponent project with platform specific files. Namely, **.ios** and **.android** files. 

Is there a suggested way of doing this, rather than using `Platform.OS` for platform specific code in the project?

**Comment by jesseruder** [comment]
.ios and .android files should work the same way as in raw React Native. Did they not work when you tried?

**Comment by ChenLi0830** [comment]
Hi @jesseruder, thank you for clearing that! There was only one entry file main.js. I guess that made me mistakenly assumed Exponent doesn't support .ios and .android files. 

I just tried using .ios.js and .android.js and they worked perfectly.
