### ISSUE TITLE
Versioning Error When Submitting to Google Play

### ISSUE THREAD

**Issue by ChenLi0830** [exponent/exponent#73]
I prevously submitted a standalone app built with Exponent to Google Play. Now when I am submitting an updated version, I see the following error.

<img width="1440" alt="screen shot 2017-03-09 at 5 21 53 pm" src="https://cloud.githubusercontent.com/assets/9557418/23778021/f65f0782-04ec-11e7-947a-d33b45603411.png">

I have updated exp.json file from "version": "1.0.1" to "version": "1.1.0", and I am wondering why am I still having this error?

**Comment by jesseruder** [comment]
Hey sorry just saw this. You need to use this key https://docs.expo.io/versions/v14.0.0/guides/configuration.html#versioncodeversion-number-required-by-google-play-increment-by-one-for-each-release-httpsdeveloperandroidcomstudiopublishversioninghtml in exp.json.

**Comment by ChenLi0830** [comment]
@jesseruder Perfect, thank you!
