### ISSUE TITLE
exp convert: brand name change and related warnings and error

### ISSUE THREAD

**Issue by idibidiart** [exponent/exponent#77]
when running 'exp convert'

```
Running npm install, this may take a few minutes.
-----------------------------------------------------
npm WARN deprecated exponent@13.1.0: The 'Exponent' project has beeen renamed to 'Expo'. This package is now named 'expo'.
npm WARN deprecated @exponent/vector-icons@4.0.0: The 'Exponent' project has been renamed to 'Expo'. This package is now named '@expo/vector-icons'.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global marked@0.3.6 should be installed with -g
```

Also, at the end it says:

```
1. Find your AppRegistry.registerComponent('YourApplicationName', () => YourRootComponent) call and replace it with Expo.registerRootComponent(YourRootComponent) (you will need to import Expo from 'expo')
```

But the package it installs is still called 'exponent' not 'expo'

Also, for now, until the name chsange fixes are in, .babelrc should be:
```
{
  "presets": ["babel-preset-exponent"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
```

the env property is currently missing 

More urgently, Expo looks for index.js rather than index.platform.js and throws an error

**Comment by jesseruder** [comment]
Thanks for the issue. `exp convert` is a little out of date - we'll take a look at it soon.

**Comment by idibidiart** [comment]
For now, how do I fix the "index.js" issue not found? I obviously want to have the app run on both ios and android so is there a way to hook into the XDE process and pick the right file and write it to index.js? Or what do u suggest? Thanks a lot for your help.

**Comment by jesseruder** [comment]
You can just create a main.js file that imports index.js. That import will correctly pick up index.android.js and index.ios.js.

**Comment by idibidiart** [comment]
if i have ```import 'index'``` you're saying it will import both? (is that standard es6 import behavior?)  and wouldn't that be duplicating Expo.registerRootComponent ? which one will it pick?

I'm confused. How do we get to choose whether we run the IOS app or the Android app?

**Comment by idibidiart** [comment]
Thanks for you help on Slack!!

Summary to close this issue is:

It'd be nice to make it so main.js is not needed. It should pick the right entry point based on what you choose for device platform... that would be abundantly clear.. as opposed to having to figure out that a main.js file is needed with  

```import 'index.js'```

(it's not standard RN and it's a little counter intuitive as index.js doesn't exist till packager runs so basically people have to know that packager ids going to produce index.js and people doing this first time could get confused)

**Comment by sonaye** [comment]
have you tried adding `"main": "index.js"` to your `package.json`?

**Comment by idibidiart** [comment]
Yes, we're working thru errors despite having done that, reset npm cache and restarted the packager from XDE on every new attempt

**Comment by idibidiart** [comment]
Same error:  Cannot find entry file index.js in any of the roots

**Comment by sonaye** [comment]
Just tested it, working perfectly for me with `index.js` as the entry point, after defining it in `package.json`.

**Comment by idibidiart** [comment]
so I have ```"main": "main.js"``` and my problem was I had a typo in the name of index.ios.js (was index.io.js) I'm not sure if both ```"main": "main.js"``` and ```"main": "index.js"``` are valid. I'm using ```"main": "main.js"``` and ```import 'index'```

**Comment by sonaye** [comment]
You should only use one and not both.

**Comment by idibidiart** [comment]
Hi, by "both" I mean if both ways work not using  both ways at the same time :)
